controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: ""
        en: en
    requirements:
        _locale: en|fr
    defaults:
        _locales: fr
kernel:
    resource: ../../src/Kernel.php
    type: annotation
